[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444748"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.normal]
black = "#323536"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.5

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 9
y = 9
