[General]
UITheme=theme-night
ignoreMsgAboutOpenTabs=true
openPath=/home/fm39hz/Downloads/64Gram Desktop
position=@Rect(12 54 1896 1014)
savePath=/home/fm39hz/Documents/Tecapro/kho-cong-dlm/SRS
titlebar=custom
