gui:
  nerdFontsVersion: "3"
customCommands:
  - key: <c-a>
    description: Pick AI commit
    command: aicommit2
    context: files
    output: terminal
  - key: <c-n>
    description: Pick AI commit (no verify)
    command: aicommit2 --no-verify
    context: files
    output: terminal
git:
  paging:
    colorArg: always
    pager: diff-so-fancy
