listener {
    timeout = 300
    on-timeout = dms ipc call lock lock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && notify-send "Welcome back $USER!" -h string:transient:true -t 2000
}
