hl.config({ autogenerated = false })

-- NẠP ĐẦU TIÊN: Đảm bảo môi trường hệ thống thông suốt cho các app sau ăn theo
require("conf.environment")

-- Cấu trúc các module còn lại của bạn
require("conf.auto")
require("conf.monitor")
require("conf.style")
require("conf.animations")
require("conf.keybinds")
require("conf.input")
require("conf.plugins")
require("conf.rules")
