hl.config({ autogenerated = false })

-- Cấu trúc các module
require("conf.monitor")
require("conf.style")
require("conf.animations")
require("conf.input")
require("conf.plugins")
require("conf.rules")
require("conf.auto")
require("conf.mapping")
