#!/usr/bin/bash

sudo pacman -S git git-lfs
sudo pacman -S gum jq figlet wget unzip
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
curl -s https://raw.githubusercontent.com/mylinuxforwork/packages-installer/main/setup.sh | bash -s -- -s https://raw.githubusercontent.com/fm39hz/.dotfiles/main/com.fm39hz.everland.pkginst com.fm39hz.everland

# Install AUR packages
echo "Installing AUR packages..."
paru -S --needed --noconfirm \
    64gram-desktop-bin \
    7-zip-bin \
    acpi \
    adobe-source-han-sans-cn-fonts \
    adobe-source-han-serif-cn-fonts \
    adw-gtk-theme \
    alacritty \
    amazon-fonts \
    antigravity \
    anytype-bin \
    aspnet-runtime \
    aspnet-runtime-8.0 \
    aspnet-targeting-pack \
    aubio \
    aws-cli \
    aws-sdk-cpp \
    base \
    base-devel \
    bat \
    beekeeper-studio-bin \
    bind \
    blender \
    blesh-git \
    blueman \
    bluez \
    bluez-utils \
    brave-nightly-bin \
    brightnessctl \
    btop \
    bun \
    calibre-bin \
    carapace \
    cava \
    chafa \
    clang \
    cloudflared \
    cmake \
    cmatrix \
    codex-desktop-linux \
    colloid-everforest-gtk-theme-git \
    composer \
    cursor-bin \
    dart-sass \
    dbeaver \
    ddcutil \
    devin-desktop \
    devspace-bin \
    diff-so-fancy \
    dms-shell \
    docker \
    docker-buildx \
    docker-compose \
    dotnet-sdk \
    dotnet-sdk-8.0 \
    earlyoom \
    easyeffects \
    efibootmgr \
    entr \
    epubcheck \
    everforest-icon-theme-git \
    evtest \
    ex-vi-compat \
    eza \
    fastfetch \
    fcitx5-bamboo \
    fcitx5-configtool \
    fcitx5-lotus-bin \
    fd \
    ffmpegthumbnailer \
    figlet \
    fish \
    flutter-bin \
    fprintd \
    fuzzel \
    fzf \
    game-devices-udev \
    geekbench \
    ghostty \
    gimp \
    git \
    git-filter-repo \
    git-lfs \
    github-cli \
    gjs \
    gnome-bluetooth-3.0 \
    gnome-calculator \
    gnome-disk-utility \
    gnome-keyring \
    go \
    gopreload-git \
    gpsd \
    gpu-screen-recorder \
    gradia \
    graphviz \
    grc \
    greetd \
    gruvbox-dark-icons-gtk \
    gst-plugin-pipewire \
    gst-plugins-good \
    gtk-engine-murrine \
    gum \
    gvfs \
    helm \
    how-cli-bin \
    html-xml-utils \
    hyprcursor \
    hyprgraphics \
    hypridle \
    hyprland \
    hyprland-guiutils \
    hyprland-qt-support \
    hyprlang \
    hyprlauncher \
    hyprlock \
    hyprpaper \
    hyprpicker \
    hyprpolkitagent \
    hyprshot \
    hyprsunset \
    hyprtoolkit \
    hyprutils \
    hyprwayland-scanner \
    iloader-bin \
    imagemagick \
    imhex-bin \
    inetutils \
    intel-gpu-tools \
    intel-media-driver \
    intel-ucode \
    iw \
    iwd \
    jdk17-openjdk \
    joyutils \
    kdeconnect \
    keyd \
    kiro-ide \
    kitty \
    kubectl \
    kvantum \
    laigter \
    lazydocker \
    lazygit \
    libfaketime \
    libinput-multiplier \
    libnotify \
    libpulse \
    libqalculate \
    libreoffice-fresh-vi \
    libva-intel-driver \
    libva-utils \
    lightnovel-crawler-bin \
    linux-firmware \
    linux-headers \
    linux-lts \
    linux-lts-headers \
    lmstudio \
    localsend-bin \
    lshw \
    lua51 \
    luajit-tiktoken-bin \
    luarocks \
    lxsession \
    lynx \
    man-db \
    mangohud \
    matugen-bin \
    maven \
    mesa-utils \
    microsoft-edge-stable-bin \
    minikube \
    mongodb-tools-bin \
    mono \
    mpd \
    mpvpaper \
    mtr \
    nasm \
    ncdu \
    ncurses5-compat-libs \
    neofetch \
    neovide \
    neovim-nightly-bin \
    network-manager-applet \
    networkmanager \
    ninja \
    nix \
    nmap \
    nmgui-bin \
    nodejs-lts-jod \
    notification-daemon \
    notion-app-enhanced \
    noto-fonts \
    noto-fonts-cjk \
    noto-fonts-emoji \
    nouveau-fw \
    npm \
    nsxiv \
    nushell \
    nwg-look \
    obs-studio \
    obsidian \
    ocrmypdf \
    onlyoffice-bin \
    openai-codex \
    openapi-tui \
    opencode \
    openresolv \
    oracle-sqldeveloper \
    pacman-contrib \
    paru \
    pavucontrol \
    php \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulse \
    plantuml \
    plocate \
    podman \
    postman-bin \
    power-profiles-daemon \
    powerpill \
    powertop \
    python-build \
    python-installer \
    python-libtmux \
    python-oracledb \
    python-pip \
    python-pipx \
    python-psycopg2 \
    python-pywalfox \
    python312 \
    pywal-spicetify \
    qt5-wayland \
    qt5ct \
    qt6-tools \
    quickshell \
    rclone-browser \
    readest \
    resvg \
    ripgrep \
    rofi \
    rsync \
    rtl8821au-dkms-git \
    runapp \
    rust \
    s3fs-fuse \
    scalar-desktop-bin \
    secrets \
    sendme-bin \
    sesh-bin \
    shed-sh \
    sigil \
    socat \
    solaar \
    sox \
    speedtest-cli \
    spicetify-cli \
    spotify-launcher \
    spotx-git \
    sqlit \
    starship \
    steam \
    superfile \
    syntax-highlighting \
    tauri-cli \
    tesseract-data-chi_sim \
    tesseract-data-chi_tra \
    tesseract-data-eng \
    tesseract-data-jpn \
    tesseract-data-kor \
    tesseract-data-lat \
    tesseract-data-spa \
    thefuck \
    thorium-browser-avx2-bin \
    thunar \
    thunar-archive-plugin \
    thunar-media-tags-plugin \
    thunar-shares-plugin \
    thunar-vcs-plugin \
    tiled \
    tldr \
    tmux \
    tmuxp \
    todoist-appimage \
    tofi \
    tree \
    tree-sitter \
    ttf-dejavu \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    ttf-league-gothic \
    ttf-material-icons-git \
    ttf-material-symbols-variable-git \
    ttf-phosphor-icons \
    ttf-roboto \
    ttf-roboto-mono \
    ttf-times-new-roman \
    ttfautohint \
    unarchiver \
    unrar \
    unzip \
    uv \
    uwsm \
    v2rayn \
    vesktop-bin \
    visual-studio-code-bin \
    vivaldi \
    vivid \
    vlc \
    vlc-plugin-ffmpeg \
    vlc-plugin-x264 \
    vlc-plugin-x265 \
    vulkan-intel \
    waybar \
    wget \
    wine \
    wireguard-go-git \
    wireguard-tools \
    wireplumber \
    wl-clip-persist \
    wlogout \
    wlsunset \
    wmctrl \
    wtype \
    xarchiver-gtk2 \
    xclip \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-hyprland \
    xorg-xev \
    xpadneo-dkms \
    yad \
    yay-bin \
    yazi \
    yq \
    zalo \
    zathura \
    zathura-pdf-mupdf \
    zbar \
    zed \
    zellij \
    zen-browser-bin \
    zoxide \
    zram-generator \
    zsh \

echo "AUR packages installation complete!"
