#!/usr/bin/bash

sudo pacman -S git git-lfs
sudo pacman -S gum jq figlet wget unzip
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
curl -s https://raw.githubusercontent.com/mylinuxforwork/packages-installer/main/setup.sh | bash -s -- -s https://raw.githubusercontent.com/fm39hz/.dotfiles/main/com.fm39hz.everland.pkginst com.fm39hz.everland

# Install AUR packages
echo "Installing AUR packages..."
paru -S --needed --noconfirm \
    64gram-desktop-bin \
    7-zip-bin \
    acpi \
    adobe-source-han-sans-cn-fonts \
    adobe-source-han-serif-cn-fonts \
    ags-hyprpanel-git \
    alacritty \
    anytype-bin \
    app2unit-git \
    aspnet-runtime \
    aspnet-targeting-pack \
    aubio \
    aws-sdk-cpp \
    base \
    base-devel \
    beekeeper-studio-bin \
    bitwarden \
    blender \
    blueman \
    bluez \
    bluez-utils \
    brave-nightly-bin \
    brightnessctl \
    btop \
    bun-bin \
    calibre-bin \
    carapace \
    cava \
    chafa \
    clang \
    cloudflared \
    cmake \
    cmatrix \
    colloid-everforest-gtk-theme-git \
    composer \
    dart-sass \
    ddcutil \
    devspace-bin \
    diff-so-fancy \
    docker \
    docker-buildx \
    docker-compose \
    dotnet-sdk \
    dotnet-sdk-8.0 \
    dotnet-sdk-9.0 \
    earlyoom \
    efibootmgr \
    entr \
    epubcheck \
    everforest-icon-theme-git \
    eza \
    fastfetch \
    fcitx5-bamboo \
    fcitx5-configtool \
    fd \
    ffmpegthumbnailer \
    figlet \
    fish \
    flutter-bin \
    fprintd \
    fzf \
    ghostty \
    gimp \
    git \
    git-lfs \
    github-cli \
    gnome-bluetooth-3.0 \
    gnome-calculator \
    gnome-disk-utility \
    gnome-keyring \
    go \
    gopreload-git \
    gpsd \
    gpu-screen-recorder \
    graphviz \
    grc \
    greetd \
    gruvbox-dark-icons-gtk \
    gst-plugin-pipewire \
    gst-plugins-good \
    gtk-engine-murrine \
    gui-for-singbox \
    gum \
    how-cli-bin \
    html-xml-utils \
    hypridle \
    hyprland-git \
    hyprland-qt-support \
    hyprlock-git \
    hyprpaper-git \
    hyprpicker \
    hyprpolkitagent \
    hyprshot \
    hyprsunset \
    ibus \
    imagemagick \
    inetutils \
    intel-media-driver \
    intel-ucode \
    iw \
    iwd \
    jdk17-openjdk \
    kdeconnect \
    keyd \
    kitty \
    kubectl \
    kvantum \
    laigter \
    lazydocker \
    lazygit \
    libfaketime \
    libinput-multiplier \
    libnotify \
    libpulse \
    libqalculate \
    libreoffice-fresh-vi \
    libva-intel-driver \
    libva-nvidia-driver \
    libva-utils \
    lightnovel-crawler-bin \
    linux-firmware \
    linux-headers \
    linux-lts \
    lmstudio \
    localsend-bin \
    lshw \
    lua51 \
    luajit-tiktoken-bin \
    luarocks \
    lxsession \
    lynx \
    man-db \
    mariadb \
    matugen-bin \
    maven \
    microsoft-edge-stable-bin \
    minikube \
    mongodb-tools-bin \
    mono \
    mpd \
    nasm \
    neofetch \
    neovide \
    neovim-nightly-bin \
    network-manager-applet \
    networkmanager \
    ninja \
    nitch-git \
    nix \
    nmap \
    nmgui-bin \
    nodejs-lts-jod \
    notification-daemon \
    notion-app-enhanced \
    noto-fonts \
    noto-fonts-cjk \
    noto-fonts-emoji \
    nouveau-fw \
    npm \
    nsxiv \
    nushell \
    nvidia-lts \
    nwg-look \
    obs-studio \
    obsidian \
    opencode-bin \
    pacman-contrib \
    paru-bin \
    paru-debug \
    php \
    pipewire \
    pipewire-alsa \
    pipewire-jack \
    pipewire-pulse \
    plantuml \
    plocate \
    postman-bin \
    power-profiles-daemon \
    powerpill \
    powertop \
    python-build \
    python-gpustat \
    python-installer \
    python-libtmux \
    python-pip \
    python-pywalfox \
    pywal-spicetify \
    qt5-wayland \
    qt5ct \
    quickshell \
    readest \
    ripgrep \
    rofi \
    rsync \
    rtl8821au-dkms-git \
    rust \
    scalar-desktop-bin \
    secrets \
    sendme-bin \
    sigil \
    solaar \
    sox \
    speedtest-cli \
    spicetify-cli \
    spotify \
    spotx-git \
    starship \
    steam \
    superfile \
    swww \
    thefuck \
    thorium-browser-bin \
    thunar \
    thunar-archive-plugin \
    thunar-media-tags-plugin \
    thunar-shares-plugin \
    thunar-vcs-plugin \
    tiled \
    tldr \
    tmux \
    todoist-appimage \
    tofi \
    tree \
    tree-sitter \
    ttf-dejavu \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    ttf-material-icons-git \
    ttf-material-symbols-variable-git \
    ueberzug \
    unarchiver \
    unrar \
    unzip \
    uv \
    uwsm \
    vesktop-bin \
    vi \
    visual-studio-code-bin \
    vivid \
    vlc \
    vlc-plugin-ffmpeg \
    vlc-plugin-x264 \
    vlc-plugin-x265 \
    vulkan-intel \
    waybar \
    wget \
    wine \
    wireplumber \
    wlogout \
    wmctrl \
    xarchiver-gtk2 \
    xclip \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-hyprland \
    xorg-xev \
    yad \
    yay-bin \
    yazi \
    yq \
    zathura \
    zathura-pdf-mupdf \
    zed \
    zellij \
    zen-browser-bin \
    zoxide \
    zram-generator \
    zsh \

echo "AUR packages installation complete!"
