set -g mouse on
set -sg escape-time 0 
set -g exit-empty off
set -g history-limit 50000 
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g default-terminal "xterm-256color" 
set-option -ga terminal-features ",xterm-256color:RGB"

set -gq allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set-option -g status-position top
set -g popup-border-lines "rounded"
set -g popup-style "bg=#2d353b,fg=#d3c6aa"
set -g popup-border-style "bg=#2d353b,fg=#859289"

bind-key C-b display-popup -w 80% -h 70% -x C -y C -E "$HOME/go/bin/gotomux"
bind-key C-e run-shell "$HOME/go/bin/gotomux -e"
bind-key -n C-f run-shell "$HOME/go/bin/gotomux -f >/dev/null 2>&1; tmux display-message 'Frozed #{session_name}'"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g extended-keys on
set -g extended-keys-format csi-u

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'azorng/tmux-smooth-scroll'

set -g @smooth-scroll-mouse "true"
set -g @smooth-scroll-easing "linear"

set -g @plugin 'ofirgall/tmux-window-name'

set -g @plugin 'TanglingTreats/tmux-everforest'
set -g @tmux-everforest 'dark-medium'

run '~/.tmux/plugins/tpm/tpm'
